"""Adding refund models

Revision ID: 6d3580a1a767
Revises: fd2a94cab98d
Create Date: 2024-11-16 22:26:08.462748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3580a1a767'
down_revision = 'fd2a94cab98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('order_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['order_uuid'], ['order.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refund')
    # ### end Alembic commands ###
